server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27027
      database: SocialMediaUserProfileDB
      username: bilge
      password: bilge!123

jwt:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}